version: "3.9"
services:
  kiss-bridge:
    build: ../../kiss-bridge
    restart: unless-stopped
    ports:
      - "5555:5555/udp"
    entrypoint:
      - node
      - index.js
      - -t
      - "direwolf:8001"
  direwolf:
    build: direwolf
    restart: unless-stopped
    privileged: true
    ports:
      - "8001:8001"
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - "80:80"

